*&---------------------------------------------------------------------*
*& Include          ZDEV001R001_SCR
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BLK01 WITH FRAME TITLE TEXT-T01.

SELECT-OPTIONS: S_FNAME FOR GV_FNAME,
                S_PTYPE FOR GV_PTYPE.
SELECT-OPTIONS: S_FLANGU FOR GV_FLANGU DEFAULT SY-LANGU  "Function Module Language
                                       NO INTERVALS,
                S_PLANGU FOR GV_PLANGU DEFAULT SY-LANGU  "Parameter Module Language
                                       NO INTERVALS.
PARAMETERS:     P_NOINC TYPE C AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END   OF BLOCK BLK01.

SELECTION-SCREEN BEGIN OF BLOCK BLK02 WITH FRAME TITLE TEXT-T02.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(79) TEXT-C01.
SELECTION-SCREEN END   OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(79) TEXT-C02.
SELECTION-SCREEN END   OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(79) TEXT-C03.
SELECTION-SCREEN END   OF LINE.
SELECTION-SCREEN END   OF BLOCK BLK02.
